[package]
name = "gzp"
authors = ["Seth Stadick <sstadick@gmail.com>"]
version = "0.2.0"
edition = "2018"
license = "Unlicense/MIT"
readme = "README.md"
documentation = "https://docs.rs/gzp"
homepage = "https://github.com/sstadick/gzp"
repository = "https://github.com/sstadick/gzp"
categories = ["compression", "concurrency"]
keywords = ["compression", "parallel", "pigz"]
description = "Parallel Gzip Compression"

[lib]
name = "gzp"
path = "src/lib.rs"

[features]
default = ["flate2/default"]
zlib = ["flate2/zlib"]
zlib-ng-compat = ["flate2/zlib-ng-compat"]
cloudflare_zlib = ["flate2/cloudflare_zlib"]
rust_backend = ["flate2/miniz_oxide"]

[dependencies]
bytes = "1.0.1"
flate2 = { version = "~1", default-features = false }
futures = "0.3.16"
num_cpus = "1.13.0"
thiserror = "1.0.26"
tokio = { version = "1.9.0", features = ["sync", "rt-multi-thread"] }

[dev-dependencies]
proptest = "1.0.0"
tempfile = "3.2.0"
