[package]
name = "gzp"
authors = ["Seth Stadick <sstadick@gmail.com>"]
version = "0.3.1-alpha.0"
edition = "2018"
license = "Unlicense/MIT"
readme = "README.md"
documentation = "https://docs.rs/gzp"
homepage = "https://github.com/sstadick/gzp"
repository = "https://github.com/sstadick/gzp"
categories = ["compression", "concurrency"]
keywords = ["compression", "parallel", "pigz"]
description = "Parallel Gzip Compression"

[lib]
name = "gzp"
path = "src/lib.rs"

[features]
default = []
parsnap_default = ["parsnap"]
pargz_default = ["pargz", "flate2_default"]
pargz = [] # pargz enables features within the crate
parsnap = ["snap"] # parsnap enable features within the crate
flate2_default = ["flate2/default"]
zlib = ["flate2/zlib"]
zlib-ng-compat = ["flate2/zlib-ng-compat"]
cloudflare_zlib = ["flate2/cloudflare_zlib"]
rust_backend = ["flate2/miniz_oxide"]

[dependencies]
bytes = "1.0.1"
flate2 = { version = "~1", default-features = false, optional = true }
futures = {version = "0.3.16", features = ["thread-pool"] }
num_cpus = "1.13.0"
thiserror = "1.0.26"
tokio = { version = "1.9.0", features = ["sync", "rt-multi-thread"] }
snap = { version = "~1", optional = true }
flume = "0.10.8"

[dev-dependencies]
proptest = "1.0.0"
tempfile = "3.2.0"
criterion = "0.3"

[[bench]]
name = "bench"
harness = false
